message: Hello world - this message is from github
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sys
    username: root
    password: Password1#
  jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQLDialect 
  jpa.hibernate.ddl-auto: update
  jpa.show-sql: true
server:
 port: 8082
 
